version: '3'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    network_mode: "bridge"
    restart: unless-stopped
    ports: 
      - 7878
    environment:
      - "TZ=Europe/paris"
      - PUID=1002
      - PGID=1002
    volumes:
      - /home/fsx/docker-storage/radarr/config:/config
      - /media/films:/movies
      - /media/dl:/downloads
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=7878'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:radarr.___your_domain_name___'
      - 'traefik.backend=radarr'
      - "traefik.frontend.auth.basic=___user___:__user_password___"


  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - 9117
    environment:
      - "TZ=Europe/Paris"
      - PUID=1002
      - PGID=1002
    volumes:
      - /home/fsx/docker-storage/jackett/config:/config
      - /media/dl/blackhole:/downloads
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9117'
      - 'traefik.frontend.entryPoints=http,https'
      - 'traefik.frontend.rule=Host:jackett.___your_domain_name___'
      - 'traefik.backend=jackett'
      - "traefik.frontend.auth.basic=___user___:__user_password___"
