version: '2'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    network_mode: "bridge"
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - "TZ=Europe/paris"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/fsx/docker-storage/plex/config:/config
      - /home/fsx/docker-storage/plex/temp:/transcode
      - /media:/data
      - "/etc/localtime:/usr/share/zoneinfo/posixrules:ro" 
    labels:
      - "traefik.port=32400"
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:___your_domain_name___'
      - 'traefik.backend=plex'
#      - 'traefik.frontend.auth.basic=___user___:____hash____'
      - 'traefik.frontend.entryPoints=http,https'

